---
apiVersion: v1
kind: Secret
metadata:
  name: ordersx2w-app-repo
  namespace: devhub
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/devhub-mad/ordersx2w-app-gitops
